[workspace]
resolver = "2"
members = [
  "notify",
  "notify-types",
  "notify-debouncer-mini",
  "notify-debouncer-full",
  "file-id",
  # internal
  "examples"
  #"examples/hot_reload_tide" until https://github.com/rustsec/rustsec/issues/501 is resolved
]
exclude = ["examples/hot_reload_tide"]
